### ISSUE TITLE
分享一个seed

### ISSUE THREAD

**Issue by kongdelu** [jiangydev/aptos-node#1]
seeds:
  42aa5a9a4ab061b6c5581d1d5aa47e1c53de0452288c4b44a1a50e5c6c38bf16:
      addresses:
      - "/ip4/118.195.204.217/tcp/6180/ln-noise-ik/42aa5a9a4ab061b6c5581d1d5aa47e1c53de0452288c4b44a1a50e5c6c38bf16/ln-handshake/0"
      role: Upstream

**Comment by jiangydev** [comment]
感谢分享，已添加
