### ISSUE TITLE
Service support 24/7

### ISSUE THREAD

**Issue by zhanglin2** [jiangydev/aptos-node#2]
Service support 24/7

d003e395aa76505c29e6e9e74d1f74892a7d8a43f3f24e588c1267c62001b64f:
  addresses:
  - "/ip4/124.221.49.235/tcp/6180/ln-noise-ik/d003e395aa76505c29e6e9e74d1f74892a7d8a43f3f24e588c1267c62001b64f/ln-handshake/0"
  role: "Upstream"

已更新

**Comment by Skedush** [comment]
2ae2cf1f334b72ac987fed7e66cb362da9a4f594a31372670c30d9951fb3823a:
  addresses:
  - "/dns4/www.deepleep.com/tcp/6180/ln-noise-ik/<2ae2cf1f334b72ac987fed7e66cb362da9a4f594a31372670c30d9951fb3823a>/ln-handshake/0"
  role: Upstream

**Comment by ahtbatd** [comment]
cfcab2df1416abac68b893ae2608e1d334c97de9cfd66326ce6b2a19b745733e:
            addresses:
            - "/ip4/110.40.182.212/tcp/6180/ln-noise-ik/cfcab2df1416abac68b893ae2608e1d334c97de9cfd66326ce6b2a19b745733e/ln-handshake/0"
            role: "Upstream"
        2f04a89ad150eb78ecf9c8358214e4bd5a4c2f0dbf5148b0a84c0f11e761231f:
            addresses:
            - "/ip4/42.192.143.216/tcp/6180/ln-noise-ik/2f04a89ad150eb78ecf9c8358214e4bd5a4c2f0dbf5148b0a84c0f11e761231f/ln-handshake/0"
            role: "Upstream"
        68ccb17f07d1788c647244a44747423a81d0de8e671ffa16ba6a8b71229c883c:
            addresses:
            - "/ip4/110.40.154.249/tcp/6180/ln-noise-ik/68ccb17f07d1788c647244a44747423a81d0de8e671ffa16ba6a8b71229c883c/ln-handshake/0"
            role: "Upstream"
        7325e7508f466ba1673d39aac49b4c1058149bed05fd66e663c2d7c5f9e5263b:
            addresses:
            - "/ip4/1.14.125.22/tcp/6180/ln-noise-ik/7325e7508f466ba1673d39aac49b4c1058149bed05fd66e663c2d7c5f9e5263b/ln-handshake/0"
            role: "Upstream"

**Comment by jiangydev** [comment]
感谢，已添加到节点中

**Comment by jiangydev** [comment]
> Service support 24/7
> 
> 704d8bed992217075cda6a5bef9f476f823cbe79fe13718029d9f172aea1391e: addresses:
> 
> * "/ip4/121.4.86.46/tcp/6180/ln-noise-ik/704d8bed992217075cda6a5bef9f476f823cbe79fe13718029d9f172aea1391e/ln-handshake/0"
>   role: "Upstream"

您的节点不通，先注释了，恢复后留言

**Comment by jiangydev** [comment]
> 2ae2cf1f334b72ac987fed7e66cb362da9a4f594a31372670c30d9951fb3823a: addresses:
> 
> * "/dns4/www.deepleep.com/tcp/<Port_Number>/ln-noise-ik/<2ae2cf1f334b72ac987fed7e66cb362da9a4f594a31372670c30d9951fb3823a>/ln-handshake/0"
>   role: Upstream

本周节点已更新，请做一下升级，谢谢

**Comment by jiangydev** [comment]
> ```
>    cfcab2df1416abac68b893ae2608e1d334c97de9cfd66326ce6b2a19b745733e:
>         addresses:
>         - "/ip4/110.40.182.212/tcp/6180/ln-noise-ik/cfcab2df1416abac68b893ae2608e1d334c97de9cfd66326ce6b2a19b745733e/ln-handshake/0"
>         role: "Upstream"
>     2f04a89ad150eb78ecf9c8358214e4bd5a4c2f0dbf5148b0a84c0f11e761231f:
>         addresses:
>         - "/ip4/42.192.143.216/tcp/6180/ln-noise-ik/2f04a89ad150eb78ecf9c8358214e4bd5a4c2f0dbf5148b0a84c0f11e761231f/ln-handshake/0"
>         role: "Upstream"
>     68ccb17f07d1788c647244a44747423a81d0de8e671ffa16ba6a8b71229c883c:
>         addresses:
>         - "/ip4/110.40.154.249/tcp/6180/ln-noise-ik/68ccb17f07d1788c647244a44747423a81d0de8e671ffa16ba6a8b71229c883c/ln-handshake/0"
>         role: "Upstream"
>     7325e7508f466ba1673d39aac49b4c1058149bed05fd66e663c2d7c5f9e5263b:
>         addresses:
>         - "/ip4/1.14.125.22/tcp/6180/ln-noise-ik/7325e7508f466ba1673d39aac49b4c1058149bed05fd66e663c2d7c5f9e5263b/ln-handshake/0"
>         role: "Upstream"
> ```

您的节点不通，先注释了，恢复后留言

**Comment by zhanglin2** [comment]
d003e395aa76505c29e6e9e74d1f74892a7d8a43f3f24e588c1267c62001b64f:
  addresses:
  - "/ip4/124.221.49.235/tcp/6180/ln-noise-ik/d003e395aa76505c29e6e9e74d1f74892a7d8a43f3f24e588c1267c62001b64f/ln-handshake/0"
  role: "Upstream"

09d4e303d10cf7673651e858b48644128a4a6b9eaa08d7aeee30eeefe386d817:
  addresses:
  - "/ip4/124.221.78.75/tcp/6180/ln-noise-ik/09d4e303d10cf7673651e858b48644128a4a6b9eaa08d7aeee30eeefe386d817/ln-handshake/0"
  role: "Upstream"


总共2台，均更新，7/24在线，麻烦更新下，谢谢

**Comment by jiangydev** [comment]
> d003e395aa76505c29e6e9e74d1f74892a7d8a43f3f24e588c1267c62001b64f: addresses:
> 
> * "/ip4/124.221.49.235/tcp/6180/ln-noise-ik/d003e395aa76505c29e6e9e74d1f74892a7d8a43f3f24e588c1267c62001b64f/ln-handshake/0"
>   role: "Upstream"
> 
> 09d4e303d10cf7673651e858b48644128a4a6b9eaa08d7aeee30eeefe386d817: addresses:
> 
> * "/ip4/124.221.78.75/tcp/6180/ln-noise-ik/09d4e303d10cf7673651e858b48644128a4a6b9eaa08d7aeee30eeefe386d817/ln-handshake/0"
>   role: "Upstream"
> 
> 总共2台，均更新，7/24在线，麻烦更新下，谢谢

已添加

**Comment by oqdbpo2013** [comment]
f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c:
            addresses:
            - "/dns4/61.146.17.70/tcp/6182/ln-noise-ik/f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c/ln-handshake/0"
            role: "Upstream"
