### ISSUE TITLE
分享节点

### ISSUE THREAD

**Issue by Evina-17** [jiangydev/aptos-node#3]
fd5e08af858d3f45f036e77c46e123d474edcabe781b8975629f4df440460e00:
  addresses:
  - "/ip4/49.234.88.171
/tcp/6180/ln-noise-ik/fd5e08af858d3f45f036e77c46e123d474edcabe781b8975629f4df440460e00/ln-handshake/0"
  role: "Upstream"

**Comment by jiangydev** [comment]
已添加，感谢

**Comment by oqdbpo2013** [comment]
f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c:
            addresses:
            - "/dns4/61.146.17.70/tcp/6182/ln-noise-ik/f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c/ln-handshake/0"
            role: "Upstream"
