### ISSUE TITLE
组装节点 seeds

### ISSUE THREAD

**Issue by NOrh-123** [jiangydev/aptos-node#4]
85f06a104cdf5b650e2a670ecc3bf8f49ba90458cda76955b44c9f3046e77d18:
  addresses:
  - "/ip4/101.35.222.148/tcp/6180/ln-noise-ik/85f06a104cdf5b650e2a670ecc3bf8f49ba90458cda76955b44c9f3046e77d18/ln-handshake/0"
  role: "Upstream"

**Comment by jiangydev** [comment]
已添加，感谢

**Comment by oqdbpo2013** [comment]
f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c:
            addresses:
            - "/dns4/61.146.17.70/tcp/6182/ln-noise-ik/f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c/ln-handshake/0"
            role: "Upstream"
