### ISSUE TITLE
个人节点

### ISSUE THREAD

**Issue by gbossers** [jiangydev/aptos-node#5]
50ccec7d2f3fe311c5e75803b63fab01dd60a817605a216c7a103c0901861f25:
  addresses:
  - "/ip4/128.199.194.51/tcp/6180/ln-noise-ik/50ccec7d2f3fe311c5e75803b63fab01dd60a817605a216c7a103c0901861f25/ln-handshake/0"
  role: "Upstream"

**Comment by jiangydev** [comment]
谢谢，已添加

**Comment by gbossers** [comment]
146b78788ab345627d29f21a671273b1ba3f5d96f7ff3d72e685996cd122097b:
	addresses:
	- "/dns4/178.62.111.50/tcp/6180/ln-noise-ik/146b78788ab345627d29f21a671273b1ba3f5d96f7ff3d72e685996cd122097b/ln-handshake/0"
	role: Upstream

**Comment by oqdbpo2013** [comment]
f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c:
            addresses:
            - "/dns4/61.146.17.70/tcp/6182/ln-noise-ik/f02a8ce0de2b656d9f25bf5eba93163ab4f683312c57c5e194c9c02c28fcce5c/ln-handshake/0"
            role: "Upstream"
